server:
  port: 8787
  shutdown: GRACEFUL
spring:
  application:
    name: FOOD-APP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

